version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: campusphoto_redis_experiment
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --maxmemory 1gb 
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: campusphoto_postgres_experiment
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: campusphoto
      POSTGRES_USER: campusphoto_user
      POSTGRES_PASSWORD: campusphoto_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campusphoto_user -d campusphoto"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: campusphoto_backend_experiment
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://campusphoto_user:campusphoto_password@postgres:5432/campusphoto
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    command: >
      sh -c "
        pip install redis &&
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/experiment/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 监控服务
  glances:
    image: nicolargo/glances:latest
    container_name: campusphoto_monitor
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    command: glances -w --port 61208 --bind 0.0.0.0

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: campusphoto_experiment_network
